name: UserStats
main: me.jfro.minecraft.UserStatsPlugin
author: Jfro
website: http://bukkit.org
version: 1.0b1
commands:
    stats:
        description: Commands for display stats about yourself or another player.
        usage: |
            /<command> - Displays your stats.
            /<command> <player> - Displays stats for given player.
permissions:
    stats.self:
        description: Allows player to see their own stats
        default: true
    stats.other:
        description: Allows player to see stats of other players
        default: false
  